[phases.setup]
cmds = [
    "find . -type d -name '__pycache__' -exec rm -r {} +",
    "find . -type f -name '*.pyc' -delete"
]

[start]
cmd = "python3 bot.py"

[phases.install]
nixPkgs = ["python3", "python3Packages.pip"]