services:
  - type: web
    name: discord-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: /opt/render/project/python/bin/python bot.py
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18 