services:
  - type: web
    name: discord-bot
    env: python
    runtime: python3
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python3 bot.py
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18 