services:
  - type: worker
    name: discord-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 main.py
    disk:
      name: sqlite-data
      mountPath: /data
      sizeGB: 1
    envVars:
      - key: RENDER_DB_PATH
        value: /data
      - key: DISCORD_TOKEN
        sync: false 